### ISSUE TITLE
Issue fixed in #17, but master docker image failing

### ISSUE THREAD

**Issue by charlottestjohn** [buildkite-plugins/buildkite-plugin-tester#18]
Hey! We're hitting the issues that were fixed in #17 - but it looks like the docker image has not been released yet. The badge in the README.md indicates that the build might be failing! 

Just thought we'd pass that along! ^_^ 
Thanks!

**Comment by toolmantim** [comment]
Thanks for the heads up @charlottestjohn — I've fixed that now, and the docker image is up to date 🙌🏼
