### ISSUE TITLE
Please support BATS 1.2.0?

### ISSUE THREAD

**Issue by petemounce** [buildkite-plugins/buildkite-plugin-tester#28]
BATS 1.2.0 came out in April - would you mind pushing an updated image please? https://github.com/bats-core/bats-core/releases/tag/v1.2.0

**Comment by petemounce** [comment]
cc @toolmantim @lox

**Comment by toolmantim** [comment]
I just looked into this for you @petemounce, but I believe this is blocked on https://github.com/bats-core/bats-core/issues/315#issuecomment-629806607 — when that's resolved, we can cut a new version of plugin-tester that depends on it!

**Comment by petemounce** [comment]
Ah, thanks very much for checking.

(I'm trying to find out where this load.bash is coming from (where BATS_PATH is, in the image), or whether that is optional, for work I'm doing adding some tests to https://github.com/seek-oss/docker-ecr-cache-buildkite-plugin/pull/26 .)

**Comment by toolmantim** [comment]
Sounds like some hairy debugging!

`BATS_PATH` is defined here: https://github.com/buildkite-plugins/buildkite-plugin-tester/blob/master/Dockerfile#L35

But I _think_ you can leave out the `load "$BATS_PATH/load.bash"` line from your bats tests, and things will still work? 🤔

**Comment by petemounce** [comment]
It turned out that I was struggling with the fact that on my Windows host, CRLF line-endings. Inside the linux container, LF is the expectation. So, yeah, tripped over cross-platform stuff 💯 for the win! Sorted now, and filed seek-oss/docker-ecr-cache-buildkite-plugin#27 for what I hope is a better fix.

**Comment by toolmantim** [comment]
Sounds annoyingly tricky! Glad you got it sorted, and thanks for contributing that PR. I’ll leave this open tho, to track the BATS 1.2.0 upgrade 👍🏼

**Comment by pzeballos** [comment]
Hey folks! We are going to work on upgrading to BATS 1.5 (it's in our backlog). Feel free to create a PR 🙏🏻

**Comment by pzeballos** [comment]
I'm going to reopen this one so we can track it 😊 At the moment the version of BATS is 1.5 and the plan is to upgrade it to that one. No ETA yet, but if you want to create a PR for this, we'll make sure the review it as soon as possible!

**Comment by toolmantim** [comment]
This was done in #44 with the BATS 1.7.0 upgrade 👍🏼
