### ISSUE TITLE
Broke our build

### ISSUE THREAD

**Issue by kevinburkesegment** [buildkite-plugins/buildkite-plugin-tester#46]
We used to have this:

```
# https://github.com/buildkite-plugins/buildkite-plugin-tester
load "$BATS_PATH/load.bash"
```

However, at least one of our agents downloaded a new version of the buildkite/plugin-tester image, which no longer loads load.bash:

```
bats: /load.bash does not exist
```

So I read through the README and found that this has been changed to BATS_PLUGIN_PATH, and now I am getting the opposite issue, on another agent that cached an older version of plugin-tester.

```
bats: /load.bash does not exist
```

Updating our plugin's tests has been a super finicky process. It would be nice if things that aren't usually expected to break - images - didn't cause more unexpected failures.

**Comment by toote** [comment]
Sorry for the delay in getting back to you and the inconvenience caused.

This project has releases that are versioned semantically to identify possible breaking changes. If your pipeline uses the `buildkite/plugin-tester` image, that means it will always use whatever the `latest` tag points to. And that doesn't have any regard of the fact that it may have changes that are incompatible and may be different from agent to agent depending on when it is run.

As a good practice for stable tests, we would suggest you pin that image to the version you know is compatible with your tests (`v2.0.0` in your case). Just like we had to do in other plugins after the last releases :sweat_smile:
