### ISSUE TITLE
Release 4 break stub/unstub in bats-mock

### ISSUE THREAD

**Issue by franklychilled** [buildkite-plugins/buildkite-plugin-tester#59]
I had to fix my version to v3.0.1 as v.4.0.1 didn't allows me to stub anymore the buildkite-agent

Unfortunately, when looking at https://github.com/buildkite-plugins/buildkite-plugin-tester/compare/v3.0.1...v4.0.0 I can see the new source https://github.com/buildkite-plugins/bats-mock/archive/v2.1.0.tar.gz but it is not visible publicly. So I have no idea of the change required. The doc is also referencing the original repo too.

I don't expect any breaking changes with `stub` therefore.

# Sample Bat tests
https://github.com/iress/junit-slack-notification-buildkite-plugin/blob/main/tests/command.bats

# Output running v4.0.0
![image](https://user-images.githubusercontent.com/49401184/224375617-c2030d89-61e3-42ad-83ff-36776f08f3d6.png)

# affected code
```
stub buildkite-agent 'artifact download : echo Download artifacts'
```

```
unstub buildkite-agent
```

# Workaround:
fixed version - https://github.com/iress/junit-slack-notification-buildkite-plugin/pull/9/files

**Comment by toote** [comment]
Sorry to hear that it broke your workflow... but what you are experiencing is exactly the reason why we did a major release.

I highly doubt that your plugin is calling `buildkite-agent artifact download` without any additional parameters. Based on that, as you can see in the [description of the 4.0.0 release](https://github.com/buildkite-plugins/buildkite-plugin-tester/releases/tag/v4.0.0) it specifically states that it updated the dependency of bats-mock (responsible for stubs) and one of the changes explicitly listed there is: _stubs that received additional parameters will now fail_.

You can solve it by either specifying parameters explicitly or just `*` to match any **single** paramter.

**Comment by franklychilled** [comment]
> Sorry to hear that it broke your workflow... but what you are experiencing is exactly the reason why we did a major release.
> 
> I highly doubt that your plugin is calling `buildkite-agent artifact download` without any additional parameters. Based on that, as you can see in the [description of the 4.0.0 release](https://github.com/buildkite-plugins/buildkite-plugin-tester/releases/tag/v4.0.0) it specifically states that it updated the dependency of bats-mock (responsible for stubs) and one of the changes explicitly listed there is: _stubs that received additional parameters will now fail_.
> 
> You can solve it by either specifying parameters explicitly or just `*` to match any **single** paramter.

Thank you for your reply
